#!/bin/sh
echo '<p> o vagelis den tha erthei oute simera sto ergastirio, opote katalaves Grisiel </p>' >../public_html/Team_5.html
echo '<p> i angeliki irthe simera </p>' >>../public_html/Team_5.html 
<h> O xavales sou </h>
<h1> O Vaggelis einai panta sthn wra tou </h1>
